notifications:
  email: false

branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+\.\d+/

language: node_js
cache:
  yarn: true
node_js:
  - '10'

matrix:
  fast_finish: true

install:
  - yarn install --frozen-lockfile --non-interactive

script:
  - yarn run build
  - yarn run check
  - yarn run test --coverage
  - ls src
  - cat coverage/lcov.info
  - yarn run codecov
