blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/@0no-co/wonka/discussions
    about: Ask questions and discuss with other community members
  - name: Join the Discord
    url: https://discord.gg/3EYgqrYJFS
    about: Chat with maintainers and other community members
